# Generated by Django 5.0 on 2023-12-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='file_id',
            new_name='file',
        ),
    ]
